# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title:
email:
description: > # this means to ignore newlines until "baseurl:"

baseurl: "/simsec-luminate" # the subpath of your site, e.g. /blog
url: "https://objectively.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username:
github_username:
seo_image_path: #'/images/media/filename.jpg'

# Build settings
markdown: kramdown
gems:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - node_modules
  - package.json

timezone: America/New_York

# Folder Structure
source: ./source
# sass_dir: source/css

contentful:
  spaces:
    - index: # Jekyll _data folder identifier - Required
        space: ENV_SIMSEC_CONTENTFUL_SPACE_ID         # Required
        access_token: ENV_SIMSEC_CONTENTFUL_ACCESS_TOKEN
        base_path: ./source         # Optional - Defaults to Current directory
        destination: /contentful # Optional - Defaults to _data/contentful/spaces
        all_entries: true
        cda_query:
          content_type: index
    - theme:
        space: ENV_SIMSEC_CONTENTFUL_SPACE_ID
        access_token: ENV_SIMSEC_CONTENTFUL_ACCESS_TOKEN
        base_path: ./source
        destination: /contentful
        all_entries: true
        cda_query:
          content_type: theme
    - about:
        space: ENV_SIMSEC_CONTENTFUL_SPACE_ID
        access_token: ENV_SIMSEC_CONTENTFUL_ACCESS_TOKEN
        base_path: ./source
        destination: /contentful
        all_entries: true
        cda_query:
          content_type: about
    - recommendation:
        space: ENV_SIMSEC_CONTENTFUL_SPACE_ID
        access_token: ENV_SIMSEC_CONTENTFUL_ACCESS_TOKEN
        base_path: ./source
        destination: /contentful
        all_entries: true
        cda_query:
          content_type: recommendation
    - insight:
        space: ENV_SIMSEC_CONTENTFUL_SPACE_ID
        access_token: ENV_SIMSEC_CONTENTFUL_ACCESS_TOKEN
        base_path: ./source
        destination: /contentful
        all_entries: true
        cda_query:
          content_type: insight
    - projectDetails:
        space: ENV_SIMSEC_CONTENTFUL_SPACE_ID
        access_token: ENV_SIMSEC_CONTENTFUL_ACCESS_TOKEN
        base_path: ./source
        destination: /contentful
        all_entries: true
        cda_query:
          content_type: projectDetails
    - figures:
        space: ENV_SIMSEC_CONTENTFUL_SPACE_ID
        access_token: ENV_SIMSEC_CONTENTFUL_ACCESS_TOKEN
        base_path: ./source
        destination: /contentful
        all_entries: true
        cda_query:
          content_type: figure
    - forewordPage:
        space: ENV_SIMSEC_CONTENTFUL_SPACE_ID
        access_token: ENV_SIMSEC_CONTENTFUL_ACCESS_TOKEN
        base_path: ./source
        destination: /contentful
        all_entries: true
        cda_query:
          content_type: forewordPage

page_gen:
  - data: 'data.contentful.insight.insight'
    template: 'insight_template'
    name: 'page_title'
    dir: 'insights'
  - data: 'data.contentful.recommendation.recommendation'
    template: 'recommendation_template'
    name: 'page_title'
    dir: 'recommendations'
  - data: 'data.contentful.theme.theme'
    template: 'theme_template'
    name: 'page_title'
    dir: 'themes'
